### ISSUE TITLE
How can I run elsa-studio on .net 8?

### ISSUE THREAD

**Issue by RGitHuben** [elsa-workflows/elsa-studio#117]
root component config doesn't work in .net 8.
builder.Services.AddRazorComponents(d=>{d.DetailedErrors=true; })
    .AddInteractiveServerComponents(op=>{
      
         op.RootComponents.RegisterCustomElsaStudioElements();
        // op.RootComponents.RegisterCustomElement<ActivityWrapper>("elsa-activity-wrapper");
    });
I removed root component config in program.cs and add Elsa.Studio.Workflows.Designer.Components.ActivityWrapper manually in app.razor but I got and error
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.ClientHandler[101]
      Received HTTP response headers after 54.1822ms - 401
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.ClientHandler[100]
      Sending HTTP request POST http://localhost:5001/elsa/api/identity/refresh-token
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.ClientHandler[101]
      Received HTTP response headers after 1.3667ms - 401
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.ClientHandler[100]
      Sending HTTP request GET http://localhost:5001/elsa/api/descriptors/activities
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.ClientHandler[101]
      Received HTTP response headers after 0.8673ms - 401
info: System.Net.Http.HttpClient.IActivityDescriptorsApi.LogicalHandler[101]
      End processing HTTP request after 84.3277ms - 401
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Refit.ApiException: Response status code does not indicate success: 401 (Unauthorized).
         at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 288
      --- End of stack trace from previous location ---
         at Elsa.Studio.Workflows.Domain.Services.RemoteActivityRegistryProvider.ListAsync(CancellationToken cancellationToken)
         at Elsa.Studio.Workflows.Domain.Services.DefaultActivityRegistry.RefreshAsync(CancellationToken cancellationToken)
         at Elsa.Studio.Workflows.Domain.Services.DefaultActivityRegistry.EnsureLoadedAsync(CancellationToken cancellationToken)
         at Elsa.Studio.Workflows.Designer.Components.ActivityWrapper.OnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Elsa.Studio.Components.StudioComponentBase.InvokeWithBlazorServiceContext(Func`1 func)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by jdevillard** [comment]
Hello , 

it seems that you have on issue regarding the authorization in server side.

It seems to be activated, but I think you don't pass any identity ? does a Authentication form appear? Have you a project to share?

**Comment by LinQiaoPorco** [comment]
Is there a time-plan for Elsa Studio template to upgrade from .NET 7 to .NET 8?

**Comment by rustam-ashurov-mcx** [comment]
....or .NET 9  : )

**Comment by KnibbsyMan** [comment]
Elsa Studio, at least as of 3.6.0, supports .NET 8, .NET 9 and .NET 10. Hope this helps!
