### ISSUE TITLE
  [Input(UIHint = InputUIHints.VariablePicker)]    Type conversion exception

### ISSUE THREAD

**Issue by doubleright** [elsa-workflows/elsa-studio#184]
System.InvalidCastException: Unable to cast object of type 'Elsa.Api.Client.Resources.WorkflowDefinitions.Models.Variable' to type 'Elsa.Api.Client.Shared.Models.WrappedInput'.
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.HandleValueChangedAsync(DisplayInputEditorContext context, Object value) in  elsa-studio\src\modules\Elsa.Studio.Workflows\Components\WorkflowDefinitionEditor\Components\ActivityProperties\Tabs\InputsTab.razor.cs:line 165
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.<>c__DisplayClass47_0.<<BuildInputEditorModels>b__1>d.MoveNext() in  elsa-studio\src\modules\Elsa.Studio.Workflows\Components\WorkflowDefinitionEditor\Components\ActivityProperties\Tabs\InputsTab.razor.cs:line 115
--- End of stack trace from previous location ---
   at Elsa.Studio.Models.DisplayInputEditorContext.UpdateValueAsync(Object value) in  elsa-studio\src\framework\Elsa.Studio.Core\Models\DisplayInputEditorContext.cs:line 128
   at Elsa.Studio.UIHints.Components.VariablePicker.OnValueChanged(SelectListItem value) in  elsa-studio\src\modules\Elsa.Studio.UIHints\Components\VariablePicker.razor.cs:line 38
   at Elsa.Studio.Components.StudioComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) in  elsa-studio\src\framework\Elsa.Studio.Shared\Components\StudioComponentBase.cs:line 52
   at Elsa.Studio.Components.StudioComponentBase.InvokeWithBlazorServiceContext(Func`1 func) in  elsa-studio\src\framework\Elsa.Studio.Shared\Components\StudioComponentBase.cs:line 77
   at MudExtensions.MudBaseInputExtended`1.SetValueAsync(T value, Boolean updateText, Boolean force)
   at MudExtensions.MudSelectExtended`1.SelectOption(Object obj)
   at MudExtensions.Extensions.TaskExtensions.AndForgetExt(Task task, TaskOption option)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

**Comment by KnibbsyMan** [comment]
Hi @doubleright,

Thanks for raising your issue but without steps to reproduce, the Elsa version you're using or a sample project of your issue, its hard to diagnose the issue you're facing. I will close this ticket but feel free to re-open it should you still be having this issue with the latest releases or you are able to provide more information.
