### ISSUE TITLE
Error running Elsa.Studio.Host.Wasm

### ISSUE THREAD

**Issue by MikeDLi** [elsa-workflows/elsa-studio#25]
Hello-

I cloned the Elsa.Studio solution(https://github.com/elsa-workflows/elsa-studio.git) and tried to run the Wasm project. The following error occurred. Any help is appreciated. Thanks.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: https://localhost:7052/_content/Elsa.Studio.DomInterop/dom.entry.js
      TypeError: Failed to fetch dynamically imported module: https://localhost:7052/_content/Elsa.Studio.DomInterop/dom.entry.js
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7052/_content/Elsa.Studio.DomInterop/dom.entry.js
TypeError: Failed to fetch dynamically imported module: https://localhost:7052/_content/Elsa.Studio.DomInterop/dom.entry.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Elsa.Studio.DomInterop.Interop.JsInteropBase.<InvokeAsync>d__6`1[[System.Double, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Users\dli5\source\repos\elsa-studio\src\framework\Elsa.Studio.DomInterop\Interop\JsInteropBase.cs:line 46
   at Elsa.Studio.DomInterop.Interop.DomJsInterop.GetVisibleHeightAsync(ElementRef elementRef, CancellationToken cancellationToken) in C:\Users\dli5\source\repos\elsa-studio\src\framework\Elsa.Studio.DomInterop\Interop\DomJsInterop.cs:line 19
   at Elsa.Studio.Workflows.Screens.EditWorkflowDefinition.Components.WorkflowEditor.UpdateActivityPropertiesVisibleHeightAsync() in C:\Users\dli5\source\repos\elsa-studio\src\modules\Elsa.Studio.Workflows\Screens\EditWorkflowDefinition\Components\WorkflowEditor.razor.cs:line 269
   at Elsa.Studio.Workflows.Screens.EditWorkflowDefinition.Components.WorkflowEditor.OnAfterRenderAsync(Boolean firstRender) in C:\Users\dli5\source\repos\elsa-studio\src\modules\Elsa.Studio.Workflows\Screens\EditWorkflowDefinition\Components\WorkflowEditor.razor.cs:line 110
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by RainerAtSpirit** [comment]
Same here. Steps to reproduce. 

* Load Elsa-Studio
* Load Workflow Definition
* Select a Workflow
* Browser throws the above error

I tried solving that by following steps in https://github.com/elsa-workflows/elsa-studio/issues/3, but still getting the same error message. 

@sfmskywalker Is there another build step required in order to run Elsa Studio locally?

**Comment by schneidersympatient** [comment]
I could fix this error (or at least I can now see and edit the actual workflow). 
Besides the npm install & npm run build in https://github.com/elsa-workflows/elsa-studio/blob/main/src/modules/Elsa.Studio.Workflows.Designer/ClientLib/package.json as described in #3 you also need to to execute the same two commands at https://github.com/elsa-workflows/elsa-studio/tree/main/src/framework/Elsa.Studio.DomInterop/ClientLib

After this I got rid of the error and could see and edit the workflow.

**Comment by sfmskywalker** [comment]
Exactly, there are two projects containing client assets that need to be built, as @schneidersympatient  mentioned.
Thanks @schneidersympatient for sharing the solution! 👍🏻

**Comment by sfmskywalker** [comment]
Closing this issue, since we have #3 that is about documenting steps to take to build from source code. Thanks everyone for your contributions to this thread!

**Comment by sebainones** [comment]
Apologies for adding this in here (as it is closed).
I'm experiencing the same issue but I have **not** cloned Elsa.Studio solution, I'm just using Elsa Studio Blazor Server based on the https://v3.elsaworkflows.io/docs/installation/elsa-studio-blazorserver documentation.
- I'm able to create a Workflow Definition (put a name and description)
- After that I get the same error as depicted in this issue:
  _"Failed to fetch dynamically imported module: https://localhost:7052/_content/Elsa.Studio.DomInterop/dom.entry.js"_
- If I click again on definitions I can see that the workflow was indeed created but again if I try to access it, the same error appears.

Could anyone point me out how I might solve this, without having cloned the source code but instead using elsa-studio-blazorserver?

**Comment by sfmskywalker** [comment]
@sebainones Can you open a new issue please and attach your project? This way we might be able to see what the issue is and take appropriate measures. Thank you.
