### ISSUE TITLE
[BUG] Error When Copying and Pasting an Activity in Elsa Studio

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-studio#259]
### Summary
An error occurs when copying and pasting an activity in the Elsa Studio workflow designer.

### Steps to Reproduce
1. Open Elsa Studio.
2. Navigate to the Workflows section.
3. Copy an existing activity.
4. Paste the copied activity.
5. Modify a property of the pasted activity.

### Expected Behavior
The activity should be pasted without any errors when trying to edit the activity.

### Actual Behavior
An error message is displayed:
```
JSError: System.ArgumentException: An item with the same key has already been added.
Key: Workflow1:8865dc2b236c105a:b22d68a302d5da19
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Elsa.Studio.Workflows.Extensions.ActivityVisitorExtensions.VisitAndMapAsync(ActivityVisitor visitor, JsonObject activity) in /Users/spike/Projects/Elsa/elsa-studio/main/src/modules/Elsa.Studio.Workflows/Extensions/ActivityVisitorExtensions.cs:line 33
   ...
```

### Environment
- Elsa Studio version: 3.3
- Browser: Edge
- Operating system: macOS

### Additional Information
This issue seems related to dictionary key handling when the same activity is pasted multiple times.

**Comment by sfmskywalker** [comment]
Fixed via 437155c39de3918ab96ebf88964e925c9dc702de
