### ISSUE TITLE
Elsa Blazor Studio: getting "HttpRequestException: Response status code does not indicate success: 401 (Unauthorized)" when running Http workflows

### ISSUE THREAD

**Issue by vsk8985** [elsa-workflows/elsa-studio#334]
I am running elsa studio with (wasm and server), while running instance for the workflows which has Http activities I am getting "**HttpRequestException: Response status code does not indicate success: 401 (Unauthorized)**" 

**When using Elsa Studio Blazor Webassembly, getting these console logs on the browser**

> ![image](https://github.com/user-attachments/assets/3f1afa1c-913b-4893-92ac-0cef2064f3d3)
> 
> **Console error log:**
> _Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
>       System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
>          at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
>          at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
>          at Elsa.Studio.Workflows.Services.WorkflowInstanceObserverFactory.CreateAsync(WorkflowInstanceObserverContext context)
>          at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.ObserveWorkflowInstanceAsync()
>          at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.UpdateObserverAsync()
>          at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.SetWorkflowInstanceAsync(WorkflowInstance workflowInstance, JournalFilter filter)
>          at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.WorkflowInstanceViewer.SelectWorkflowInstanceAsync(WorkflowInstance instance)
>          at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.WorkflowInstanceViewer.OnInitializedAsync()
>          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
>          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
>    at Elsa.Studio.Workflows.Services.WorkflowInstanceObserverFactory.CreateAsync(WorkflowInstanceObserverContext context)
>    at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.ObserveWorkflowInstanceAsync()
>    at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.UpdateObserverAsync()
>    at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.Components.Journal.SetWorkflowInstanceAsync(WorkflowInstance workflowInstance, JournalFilter filter)
>    at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.WorkflowInstanceViewer.SelectWorkflowInstanceAsync(WorkflowInstance instance)
>    at Elsa.Studio.Workflows.Components.WorkflowInstanceViewer.WorkflowInstanceViewer.OnInitializedAsync()
>    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)_
> 
> elsa/hubs/workflow-instance/negotiate?negotiateVersion=1 API is failing with 401
> ![image](https://github.com/user-attachments/assets/4e4c2077-69aa-4e10-a185-d79bc8ea7b68)
> 

**When using Elsa Studio Blazor Server, getting these console logs on the browser**
![image](https://github.com/user-attachments/assets/35bad620-3c14-46eb-89b0-4493eb28c58a)

Used the same code as from the Elsa 3.0 docs. Looks like there is some issue with SignalR. Can anyone help here.

**Comment by vsk8985** [comment]
Update:
Using 3.0.0 versions for all the Elsa packages resolved the issue and working as expected... latest versions are not stable.

**Comment by EngSayed** [comment]
Using 3.0.0 version did not work for me still (using blazor studio). 

Do we have any updates on this bug?

**Comment by VahidNaderi** [comment]
I'm experiencing the same error with a custom activity using version 3.2.3 through 3.3.0-rc6.

**Comment by teodor-ivanovv** [comment]
Still open, the latest working version is 3.2.2
It's a pity that it's not been fixed and a major blocker, making people run away from using Elsa

**Comment by teodor-ivanovv** [comment]
Still open, the latest working version is 3.2.2

@sfmskywalker, could you take a look please?

**Comment by sfmskywalker** [comment]
The issue is with the SignalR Hub endpoint, which requires authenticated requests (before, it allowed anonymous requests, exposing a major attack surface).

Elsa Studio doesn't yet send authenticated SignalR requests, which is why you're seeing 401.

The short-term work around is to simply disable the "realtime workflows" feature.
The workflow instance viewer will then fallback to a simple polling mechanism.

More information can be found here: https://github.com/elsa-workflows/elsa-core/releases/tag/3.2.3

**Comment by teodor-ivanovv** [comment]
Thanks a lot for the sufficient and significantly fast response!

Didn't have enough spare time to find this myself.

**Comment by adanbrownpaca** [comment]
Is this still open in the last release? 3.3.0?

**Comment by ricardo-abe** [comment]
> The issue is with the SignalR Hub endpoint, which requires authenticated requests (before, it allowed anonymous requests, exposing a major attack surface).
> 
> Elsa Studio doesn't yet send authenticated SignalR requests, which is why you're seeing 401.
> 
> The short-term work around is to simply disable the "realtime workflows" feature. The workflow instance viewer will then fallback to a simple polling mechanism.
> 
> More information can be found here: https://github.com/elsa-workflows/elsa-core/releases/tag/3.2.3

As my Elsa Server is hosted in a private network, I just disabled the authentication for the hub and it worked perfectly.

 //app.UseWorkflowsSignalRHubs();  
 app.MapHub<WorkflowInstanceHub>("/elsa/hubs/workflow-instance")
     .WithMetadata(new AllowAnonymousAttribute());

**Comment by ricardo-abe** [comment]
>` The issue is with the SignalR Hub endpoint, which requires authenticated requests (before, it allowed anonymous requests, exposing a major attack surface).
> 
> Elsa Studio doesn't yet send authenticated SignalR requests, which is why you're seeing 401.
> 
> The short-term work around is to simply disable the "realtime workflows" feature. The workflow instance viewer will then fallback to a simple polling mechanism.
> 
> More information can be found here: https://github.com/elsa-workflows/elsa-core/releases/tag/3.2.3

As my ElsaServer is hosted in a private network, I just made the hub allow anonymous and everything worked perfectly.

`  //app.UseWorkflowsSignalRHubs();`
`app.MapHub<WorkflowInstanceHub>("/elsa/hubs/workflow-instance") .WithMetadata(new AllowAnonymousAttribute());`
