### ISSUE TITLE
Web assembly errors using @elsa-workflows/elsa-studio-wasm within a react app for v3.3.0-rc3

### ISSUE THREAD

**Issue by JaFonz** [elsa-workflows/elsa-studio#335]
The error below is encountered when using the @elsa-workflows/elsa-studio-wasm package to embed components within a react app.
E.g.:

```
return React.createElement('elsa-workflow-definition-editor', {
        ...props,
        id: id,
        'remote-endpoint': remoteEndpoint,
        'access-token': bearerToken,
        'definition-id': definitionId,
    });
```

We are using Bearer token authentication on the server side.

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: NoServiceRegistered, Elsa.Studio.Login.Contracts.IJwtAccessor
System.InvalidOperationException: NoServiceRegistered, Elsa.Studio.Login.Contracts.IJwtAccessor
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IJwtAccessor](IServiceProvider )
   at Elsa.Studio.Login.HttpMessageHandlers.AuthenticatingApiHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Refit.RequestBuilderImplementation.<>c__DisplayClass15_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d[[Elsa.Api.Client.Resources.WorkflowDefinitions.Models.WorkflowDefinition, Elsa.Api.Client, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[Elsa.Api.Client.Resources.WorkflowDefinitions.Models.WorkflowDefinition, Elsa.Api.Client, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
--- End of stack trace from previous location ---
   at Refit.Implementation.Generated.ElsaApiClientResourcesWorkflowDefinitionsContractsIWorkflowDefinitionsApi.global::Elsa.Api.Client.Resources.WorkflowDefinitions.Contracts.IWorkflowDefinitionsApi.GetByDefinitionIdAsync(String definitionId, Nullable`1 versionOptions, CancellationToken cancellationToken)
   at Elsa.Studio.Workflows.Domain.Services.RemoteWorkflowDefinitionService.FindByDefinitionIdAsync(String definitionId, Nullable`1 versionOptions, CancellationToken cancellationToken)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.WorkflowDefinitionEditor.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by JaFonz** [comment]
Update:

Adding `builder.Services.AddLoginModule();` to Program.cs in the Elsa.Studio.Host.CustomElements project resolves the dependency injection issue above, however now there is an authentication issue. It looks like the access token being passed in as a prop to the component is not being used for the api calls from the client.

**Comment by JaFonz** [comment]
PR here to add JwtAccessor implementation and localisation for CustomElements project

https://github.com/elsa-workflows/elsa-studio/pull/341

**Comment by sfmskywalker** [comment]
Hi @JaFonz , thank you for the PR. However, as I also just commented on the PR: Upon further investigation, I realized that we do not want CustomElements to depend on the Login module, which is intended to simply be a default implementation and subject for replacement with custom SSO solutions.

Instead, CustomElements has its own authentication handler, which has been installed in a recent commit.
This handler depends on the BackendProvider component to be added as a element to the page, and confiugred to carry either a bearer token or an API key.

It's a crude solution, but will be evolved over time for better integration with custom hosting apps.

I will close this issue as solved, but let me repeat the solution:

1. Make sure to update to the latest preview version.
2. Make sure to add the <backend-provider> element as well, configure its `remote-endpoint` attribute and either its `access-token` or `api-key` attribute.
