### ISSUE TITLE
Activity variable binding save failed.

### ISSUE THREAD

**Issue by zfchai** [elsa-workflows/elsa-studio#349]
- operate

When Activity selects variable binding with type Object, clicking save triggers an exception.

![1735294776332](https://github.com/user-attachments/assets/5e766ee5-afd0-4d6e-a149-d62c9f946ab4)

- error message

```bash
[17:50:56 INF] Executed endpoint 'HTTP: POST /elsa/api/workflow-definitions'
[17:50:56 ERR] An unhandled exception occurred.
System.InvalidCastException: Unable to cast object of type 'Elsa.Workflows.Models.Output`1[System.Object]' to type 'Elsa.Workflows.Models.Input'.
at Elsa.Workflows.Serialization.Helpers.SyntheticPropertiesWriter.WriteSyntheticInputProperties(Utf8JsonWriter writer, IActivity value, ActivityDescriptor activityDescriptor, JsonSerializerOptions options)
at Elsa.Workflows.Serialization.Helpers.ActivityWriter.WriteActivity(Utf8JsonWriter writer, IActivity value, JsonSerializerOptions options, Boolean ignoreSpecializedConverters, Boolean excludeChildren, Func`2 propertyFilter)
at Elsa.Workflows.Serialization.Converters.ActivityJsonConverter.Write(Utf8JsonWriter writer, IActivity value, JsonSerializerOptions options)
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
...
```

**Comment by zfchai** [comment]
![image](https://github.com/user-attachments/assets/9279b338-e7e8-4fab-b726-79527a36f5ef)

**Comment by sfmskywalker** [comment]
Which Elsa version? I tried with RC6, but it works without any issues.

**Comment by zfchai** [comment]
RC4

**Comment by sfmskywalker** [comment]
I can't reproduce this issue, so I will close it. If still reproducible on 3.4.0-preview.xxx, please share with me your workflow JSON file. Thank you!
