### ISSUE TITLE
Issue with Workflow Activation Strategy

### ISSUE THREAD

**Issue by dallosdani** [elsa-workflows/elsa-studio#82]
**Version: 3.0.0-preview.727**

**Test case:**
In our test case we have a simple "Set Variable" activity connected to a "HTTP Endpoint" activity.
Both activities have the "Can Start Workflow" enabled and activation strategy is set to "Always".
When we execute the workflow with an API call, first activity starts, then the workflow instance is waiting for the HTTP Response and the instance become suspended. 
Next step, we initiate the API call to the "HTTP Endpoint" activity which results in the following case:
- Original workflow instance stays suspended
- New workflow instance is created and finished with endpoint call.

![image](https://github.com/elsa-workflows/elsa-studio/assets/142390211/798476c0-3c15-4f9b-8390-36f1c6dd655e)

**Expected scenario:**
When I change the activation strategy to "Correlated Singleton" and execute the workflow from the start, there is no new instance created from the "HTTP Endpoint", instead it continues the original instance and finishing that.

**Problem**
We receive the following exception where it looks like the issue connected to the Activation Strategy implementation.

System.InvalidOperationException: The provider for the source IQueryable doesn't implement IDbAsyncQueryProvider. Only providers that implement IDbAsyncQueryProvider can be used for Entity Framework asynchronous operations. For more details see http://go.microsoft.com/fwlink/?LinkId=287068.
   at System.Data.Entity.QueryableExtensions.LongCountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Elsa.EntityFrameworkCore.Common.Store`2.CountAsync(Func`2 query, CancellationToken cancellationToken)
   at Elsa.EntityFrameworkCore.Common.Store`2.CountAsync(Func`2 query, CancellationToken cancellationToken)
   at Elsa.EntityFrameworkCore.Modules.Management.EFCoreWorkflowInstanceStore.CountAsync(WorkflowInstanceFilter filter, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.CountRunningWorkflowsAsync(CountRunningWorkflowsRequest request, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.ActivationValidators.CorrelatedSingletonStrategy.GetAllowActivationAsync(WorkflowInstantiationStrategyContext context)
   at Elsa.Workflows.Runtime.Services.WorkflowHost.CanStartWorkflowAsync(StartWorkflowHostOptions options, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.CanStartWorkflowAsync(String definitionId, StartWorkflowRuntimeOptions options, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.FindStartableWorkflowsAsync(WorkflowsFilter workflowsFilter, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.FindStartableWorkflowsAsync(WorkflowsFilter workflowsFilter, CancellationToken cancellationToken)
   at Elsa.Workflows.Runtime.Services.DefaultWorkflowRuntime.FindWorkflowsAsync(WorkflowsFilter filter, CancellationToken cancellationToken)
   at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Thank you

**Comment by KnibbsyMan** [comment]
As we are now on 3.5.0 and this is a very old issue, I will close this.

Let us know if this is still an issue with the latest version!
